apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: hpa-strapapp
    namespace: default
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: strapiapp
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 90
